In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('combined.csv')

In [5]:
df

,Unnamed: 0,CRSDep,CRSDepRound,ActDep,DepDelay,Origin,Dest,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Temp,DewPoint,RelHumidity,Precip,WindDir,WindSpeed,AirPressure
0,0,2008-01-08 16:00:00,2008-01-08 16:00:00,2008-01-08 17:11:00,71,ORD,EWR,0.0,0.0,2.0,0.0,44.0,12.0,11.1,94.0,NaN,220.0,7.6,NaN
1,1,2008-01-25 17:42:00,2008-01-25 18:00:00,2008-01-25 18:13:00,31,ORD,CLE,0.0,0.0,5.0,0.0,31.0,-10.0,-18.2,51.0,0.0,220.0,14.8,1031.9
2,2,2008-01-10 16:00:00,2008-01-10 16:00:00,2008-01-10 16:01:00,1,ORD,EWR,NaN,NaN,NaN,NaN,NaN,3.3,-0.5,76.0,0.0,90.0,18.4,1010.1
3,3,2008-01-04 06:50:00,2008-01-04 07:00:00,2008-01-04 06:58:00,8,ORD,EWR,NaN,NaN,NaN,NaN,NaN,-5.0,-10.0,68.0,0.0,210.0,24.1,1028.0
4,4,2008-01-28 12:40:00,2008-01-28 13:00:00,2008-01-28 13:58:00,78,ORD,EWR,0.0,0.0,91.0,0.0,0.0,5.0,-3.3,55.0,0.0,190.0,25.9,1011.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179544,179544,2008-12-12 09:25:00,2008-12-12 09:00:00,2008-12-12 09:37:00,12,ORD,ATL,NaN,NaN,NaN,NaN,NaN,-8.3,-12.8,70.0,0.0,310.0,14.8,1018.2
179545,179545,2008-12-12 10:40:00,2008-12-12 11:00:00,2008-12-12 10:44:00,4,ORD,ATL,NaN,NaN,NaN,NaN,NaN,-10.0,-15.0,67.0,0.0,350.0,24.1,1019.3
179546,179546,2008-12-12 11:50:00,2008-12-12 12:00:00,2008-12-12 12:10:00,20,ORD,ATL,NaN,NaN,NaN,NaN,NaN,-10.6,-16.1,64.0,0.0,330.0,20.5,1020.1
179547,179547,2008-12-12 14:45:00,2008-12-12 15:00:00,2008-12-12 15:02:00,17,ORD,ATL,NaN,NaN,NaN,NaN,NaN,-11.7,-17.1,64.0,0.0,320.0,22.3,1021.8
179548,179548,2008-12-12 17:00:00,2008-12-12 17:00:00,2008-12-12 17:03:00,3,ORD,ATL,NaN,NaN,NaN,NaN,NaN,-10.0,-16.1,61.0,0.0,300.0,13.0,1022.3

In [6]:
df['CRSDepRound']

0         2008-01-08 16:00:00
1         2008-01-25 18:00:00
2         2008-01-10 16:00:00
3         2008-01-04 07:00:00
4         2008-01-28 13:00:00
                 ...
179544    2008-12-12 09:00:00
179545    2008-12-12 11:00:00
179546    2008-12-12 12:00:00
179547    2008-12-12 15:00:00
179548    2008-12-12 17:00:00
Name: CRSDepRound, Length: 179549, dtype: object

In [10]:
df.groupby('CRSDepRound').head(5).sort_values('CRSDepRound')

,Unnamed: 0,CRSDep,CRSDepRound,ActDep,DepDelay,Origin,Dest,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Temp,DewPoint,RelHumidity,Precip,WindDir,WindSpeed,AirPressure
8198,8198,2008-01-01 05:00:00,2008-01-01 05:00:00,2008-01-01 08:25:00,205,ORD,PHX,205.0,0.0,29.0,0.0,0.0,-1.7,-3.3,89.0,NaN,320.0,31.7,1010.7
4770,4770,2008-01-01 06:13:00,2008-01-01 06:00:00,2008-01-01 06:21:00,8,ORD,CLT,NaN,NaN,NaN,NaN,NaN,-2.8,-5.0,85.0,NaN,310.0,29.5,1012.0
4047,4047,2008-01-01 06:00:00,2008-01-01 06:00:00,2008-01-01 06:02:00,2,ORD,DEN,NaN,NaN,NaN,NaN,NaN,-2.8,-5.0,85.0,NaN,310.0,29.5,1012.0
1508,1508,2008-01-01 06:00:00,2008-01-01 06:00:00,2008-01-01 06:09:00,9,ORD,SYR,22.0,0.0,0.0,0.0,0.0,-2.8,-5.0,85.0,NaN,310.0,29.5,1012.0
3400,3400,2008-01-01 06:00:00,2008-01-01 06:00:00,2008-01-01 06:14:00,14,ORD,LAX,NaN,NaN,NaN,NaN,NaN,-2.8,-5.0,85.0,NaN,310.0,29.5,1012.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164867,164867,2008-12-31 20:55:00,2008-12-31 21:00:00,2008-12-31 20:58:00,3,ORD,CID,NaN,NaN,NaN,NaN,NaN,-6.7,-16.7,45.0,0.0,320.0,11.2,1030.5
167373,167373,2008-12-31 21:48:00,2008-12-31 22:00:00,2008-12-31 22:30:00,42,ORD,PIT,0.0,0.0,0.0,0.0,27.0,-7.2,-17.1,45.0,0.0,290.0,7.6,1030.5
173362,173362,2008-12-31 21:40:00,2008-12-31 22:00:00,2008-12-31 22:03:00,23,ORD,DSM,NaN,NaN,NaN,NaN,NaN,-7.2,-17.1,45.0,0.0,290.0,7.6,1030.5
175232,175232,2008-12-31 21:50:00,2008-12-31 22:00:00,2008-12-31 22:08:00,18,ORD,CVG,18.0,0.0,9.0,0.0,0.0,-7.2,-17.1,45.0,0.0,290.0,7.6,1030.5
174577,174577,2008-12-31 21:40:00,2008-12-31 22:00:00,2008-12-31 21:46:00,6,ORD,PIA,NaN,NaN,NaN,NaN,NaN,-7.2,-17.1,45.0,0.0,290.0,7.6,1030.5

In [21]:
df.groupby('CRSDepRound').head(5).sort_values('CRSDepRound').to_csv('combined_condensed_5.csv')

In [16]:
df.groupby('CRSDep').head(1).sort_values('CRSDep')

,Unnamed: 0,CRSDep,CRSDepRound,ActDep,DepDelay,Origin,Dest,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Temp,DewPoint,RelHumidity,Precip,WindDir,WindSpeed,AirPressure
8198,8198,2008-01-01 05:00:00,2008-01-01 05:00:00,2008-01-01 08:25:00,205,ORD,PHX,205.0,0.0,29.0,0.0,0.0,-1.7,-3.3,89.0,NaN,320.0,31.7,1010.7
17987,17987,2008-01-01 05:35:00,2008-01-01 06:00:00,2008-01-01 05:55:00,20,ORD,IAH,NaN,NaN,NaN,NaN,NaN,-2.8,-5.0,85.0,NaN,310.0,29.5,1012.0
1508,1508,2008-01-01 06:00:00,2008-01-01 06:00:00,2008-01-01 06:09:00,9,ORD,SYR,22.0,0.0,0.0,0.0,0.0,-2.8,-5.0,85.0,NaN,310.0,29.5,1012.0
1427,1427,2008-01-01 06:10:00,2008-01-01 06:00:00,2008-01-01 06:47:00,37,ORD,CVG,44.0,0.0,0.0,0.0,0.0,-2.8,-5.0,85.0,NaN,310.0,29.5,1012.0
4770,4770,2008-01-01 06:13:00,2008-01-01 06:00:00,2008-01-01 06:21:00,8,ORD,CLT,NaN,NaN,NaN,NaN,NaN,-2.8,-5.0,85.0,NaN,310.0,29.5,1012.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164476,164476,2008-12-31 21:10:00,2008-12-31 21:00:00,2008-12-31 21:17:00,7,ORD,FWA,NaN,NaN,NaN,NaN,NaN,-6.7,-16.7,45.0,0.0,320.0,11.2,1030.5
168043,168043,2008-12-31 21:24:00,2008-12-31 21:00:00,2008-12-31 21:37:00,13,ORD,PHL,NaN,NaN,NaN,NaN,NaN,-6.7,-16.7,45.0,0.0,320.0,11.2,1030.5
173362,173362,2008-12-31 21:40:00,2008-12-31 22:00:00,2008-12-31 22:03:00,23,ORD,DSM,NaN,NaN,NaN,NaN,NaN,-7.2,-17.1,45.0,0.0,290.0,7.6,1030.5
167373,167373,2008-12-31 21:48:00,2008-12-31 22:00:00,2008-12-31 22:30:00,42,ORD,PIT,0.0,0.0,0.0,0.0,27.0,-7.2,-17.1,45.0,0.0,290.0,7.6,1030.5
175232,175232,2008-12-31 21:50:00,2008-12-31 22:00:00,2008-12-31 22:08:00,18,ORD,CVG,18.0,0.0,9.0,0.0,0.0,-7.2,-17.1,45.0,0.0,290.0,7.6,1030.5

In [20]:
df.groupby('CRSDepRound').head(3).sort_values('CRSDepRound').to_csv('combined_condensed_3.csv')